### ISSUE TITLE
Error while building webui

### ISSUE THREAD

**Issue by turion** [gbtb/nix-stable-diffusion#9]
```
$ nix develop .#webui.amd
HEAD ist jetzt bei 737eb28 typo: cmd_opts.embedding_dir to cmd_opts.embeddings_dir
error: Anwendung des Patches fehlgeschlagen: launch.py:86
error: launch.py: Patch konnte nicht angewendet werden
error: Anwendung des Patches fehlgeschlagen: modules/paths.py:19
error: modules/paths.py: Patch konnte nicht angewendet werden
$ # put model checkpoint in place
$ HSA_OVERRIDE_GFX_VERSION=10.3.0 python launch.py
Python 3.10.7 (main, Sep  5 2022, 13:12:31) [GCC 11.3.0]
Commit hash: 737eb28faca8be2bb996ee0930ec77d1f7ebd939
Traceback (most recent call last):
  File "/home/turion/python/nix-stable-diffusion/stable-diffusion-webui/launch.py", line 205, in <module>
    prepare_enviroment()
  File "/home/turion/python/nix-stable-diffusion/stable-diffusion-webui/launch.py", line 179, in prepare_enviroment
    git_clone(stable_diffusion_repo, repo_dir('stable-diffusion'), "Stable Diffusion", stable_diffusion_commit_hash)
  File "/home/turion/python/nix-stable-diffusion/stable-diffusion-webui/launch.py", line 76, in git_clone
    current_hash = run(f'"{git}" -C {dir} rev-parse HEAD', None, f"Couldn't determine {name}'s hash: {commithash}").strip()
  File "/home/turion/python/nix-stable-diffusion/stable-diffusion-webui/launch.py", line 33, in run
    raise RuntimeError(message)
RuntimeError: Couldn't determine Stable Diffusion's hash: 69ae4b35e0a0f6ee1af8bb9a5d0016ccb27e36dc.
Command: "git" -C repositories/stable-diffusion rev-parse HEAD
Error code: 128
stdout: <empty>
stderr: fatal: Kein Git-Repository (oder irgendeines der Elternverzeichnisse): .git
```

Translation: Not a git repository.

**Comment by turion** [comment]
Possibly this is caused by #8 because the patches seem to influence parts of the code that are about cloning git repositories and import paths.

**Comment by gbtb** [comment]
Should be not relevant anymore
